#!/bin/sh

#post commit git hook which calls java AutoVersionInc.jar to commit changed buil.gradle file
#to call jar file we need full path and for build gradle also need full path
#we need post commit hook to commit changed build.gradle file, because in pre commit java can not commit, because pre commit holds git and java throws error when trying to commit on hold git instance, that is why we need post commit hook!
echo starting post commit hook
java -jar F:\\netbeansPorjects\\AutoVersionInc\\someInnerProjectTest\\AutoVersionInc.jar commit F:\\netbeansPorjects\\AutoVersionInc someInnerProjectTest/build.gradle
STATUS="${?}"
#echo $result>1
exit 0




#copy this fiel in to .git/hooks
