#!/bin/sh

#pre commit git hook which calls java AutoVersionInc.jar to parse buil.gradle and increase versions automatically
#to call jar file we need full path and for build gradle also need full path
java -jar F:\\netbeansPorjects\\AutoVersionInc\\someInnerProjectTest\\AutoVersionInc.jar F:\\netbeansPorjects\\AutoVersionInc F:\\netbeansPorjects\\AutoVersionInc\\someInnerProjectTest\\build.gradle versionBuild [aztelekomVersionCode]
STATUS="${?}"
#echo "${STATUS}"
if [ "${STATUS}" == "0" ]; 
then
	echo "commit-msg hook finished successfully. congrats"
	exit 0
else
  echo "Version increasd failed :("
  echo "Aborting the commit! Run with --no-verify if you want to ignore commit-msg hook."
  exit 1
fi



#copy this file into .git/hooks
