#!/bin/sh

#commit-msg git hook which calls java AutoVersionInc.jar to parse buil.gradle and increase versions automatically
#to call jar file we need full path and for build gradle also need full path

# 1) is path to jar file 
# 2) $1 is file location where last commit is written this argument should not be changed and should be written as it is where it is(mean should be second after file location)
# 3) path to file, which should be parsed
# 4) key which value should increas
# ....
# n) key which value should increas

# square braces for key like aztelekomVersionCode(can be allowed on any key) means that check will be provided if last commit message contains [skip ci] befor version increase for this key, so version will be increased if and only if [skip ci] will be included in last commit, otherwise if [skip ci] will not be included in last commit message, version will not be increased!




java -jar F:\\netbeansPorjects\\AutoVersionInc\\someInnerProjectTest\\AutoVersionInc.jar $1 F:\\netbeansPorjects\\AutoVersionInc\\someInnerProjectTest\\build.gradle versionBuild [aztelekomVersionCode]
STATUS="${?}"
if [ "${STATUS}" == "0" ]; 
then
	echo "commit-msg hook finished successfully. congrats"
	exit 0
else
  echo "Version increasd failed :("
  echo "Aborting the commit! Run with --no-verify if you want to ignore commit-msg hook."
  exit 1
fi




#copy this file into .git/hooks
