#!/bin/sh

#post commit git hook which calls java AutoVersionInc.jar to commit changed buil.gradle file
#to call jar file we need full path and for build gradle also need full path
#we need post commit hook to commit changed build.gradle file, because in pre commit java can not commit, because pre commit holds git and java throws error when trying to commit on hold git instance, that is why we need post commit hook!

# 1) is path to jar file
# 2) commit command (to use commit functionality)
# 3) git repo path
# 4) path to file, which should be parsed to get app version and then commited
# 5) build version key
# 6) build version name key

java -jar F:\\netbeansPorjects\\AutoVersionInc\\someInnerProjectTest\\AutoVersionInc.jar commit F:\\netbeansPorjects\\AutoVersionInc someInnerProjectTest/build.gradle versionBuild versionName
exit 0



#copy this fiel in to .git/hooks
